jobs:

- job: 'Test'
  strategy:
    matrix:
      Python36-Windows-Style:
        PYTHON_VERSION: '3.6'
        IMAGE_NAME: 'vs2017-win2016'
        TOXENV: 'style'
      Python36-Windows:
        PYTHON_VERSION: '3.6'
        IMAGE_NAME: 'vs2017-win2016'
        TOXENV: 'py36'
      Python36-Linux:
        PYTHON_VERSION: '3.6'
        IMAGE_NAME: 'ubuntu-16.04'
        TOXENV: 'py36'
      Python36-MacOSX:
        PYTHON_VERSION: '3.6'
        IMAGE_NAME: 'macos-10.13'
        TOXENV: 'py36'

  pool:
    vmImage: '$(IMAGE_NAME)'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(PYTHON_VERSION)'

  - script: python -m pip install --upgrade pip && pip install setuptools tox
    displayName: 'Install tox'

  - script: |
      tox -e $(TOXENV)
    displayName: 'unittest'

- job: 'Publish'
  dependsOn: 'Test'
  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'

  - script: python -m pip install --upgrade pip && pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: echo "placeholder"
    displayName: 'Placeholder'
